# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ea7e8d7bbda398f6aee945fdc1ffa1342d903bfddcf146afa1990c17ab75c90e49ec2c4c0b36d84fa021e6202588ddf23b5bffcbd717f15607fa4b84af2e54f

test:
  secret_key_base: ba7992ca37932e185d4c8bc0820b07773d5c135fbdff1c34b869fd25c33609412a16f395370c0f1696448ac463261084c654f31cfe1e142c490d95f88aba6c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
