# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a150787ef68bcaf6d8e10718948a5d33711592a42852e9fa12a22d23d4dad2a5fd4105712962e0dad5078757631d512fbf13e504bc4d51e4d405431f7cd1ee8

test:
  secret_key_base: a9f306d8d8f98437acf1f644fb7f6e11b67de0ece1b7c60a9693d1ba06d2b27a5fac4095195928971ad0483722f3c208483159cc4cbce59dc108a98ab14a4357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
